################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.climatecoop.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 1

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:
        - *climatecoop
        - *dcentra
        - *consenzus
        - *lacambra

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
        - *dcentra
        - *consenzus
        - *lacambra
    
    
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    MultiOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults     
        Consortiums:
            ClimateCoopConsortium:
                Organizations:
                    - <<: *lacambra
                    - <<: *climatecoop
                    - <<: *dcentra
                    - <<: *consenzus

    MultiOrgsChannel:
        Consortium: ClimateCoopConsortium
        Application:
            <<: *ApplicationDefaults

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &climatecoop
        Name: climatecoop.com
        ID: climatecoopMSP
        MSPDir: crypto-config/ordererOrganizations/climatecoop.com/msp

    - &dcentra
        Name: dcentraMSP
        ID: dcentraMSP
        MSPDir: crypto-config/peerOrganizations/dcentra.io/msp
        AdminPrincipal: Role.ADMIN

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.dcentra.io
              Port: 7051
    - &consenzus
        Name: consenzusMSP
        ID: consenzusMSP
        MSPDir: crypto-config/peerOrganizations/consenzus.io/msp
        AdminPrincipal: Role.ADMIN

        AnchorPeers:          
            - Host: peer0.consenzus.io
              Port: 7051
    - &lacambra
        Name: lacambraMSP
        ID: lacambraMSP
        MSPDir: crypto-config/peerOrganizations/lacambra.tech/msp
        AnchorPeers:
            - Host: peer0.lacambra.tech
              Port: 7051