# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.climatecoop.com:
    container_name: orderer.climatecoop.com
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=climatecoopMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/climatecoop.com/orderers/orderer.climatecoop.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050
    networks:
      - blockchain

  peer0.dcentra.io:
    container_name: peer0.dcentra.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dcentra.io
      - CORE_PEER_ADDRESS=peer0.dcentra.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dcentra.io:7051
      - CORE_PEER_LOCALMSPID=dcentraMSP
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.dcentra.io:7052
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dcentra.io/peers/peer0.dcentra.io/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.dcentra.io:
    container_name: peer1.dcentra.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dcentra.io
      - CORE_PEER_ADDRESS=peer1.dcentra.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dcentra.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dcentra.io:7051
      - CORE_PEER_LOCALMSPID=dcentraMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dcentra.io/peers/peer1.dcentra.io/msp:/etc/hyperledger/fabric/msp
    ports:
      - 8051:7051
      - 8053:7053

  peer2.dcentra.io:
    container_name: peer2.dcentra.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.dcentra.io
      - CORE_PEER_ADDRESS=peer2.dcentra.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.dcentra.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.dcentra.io:7051
      - CORE_PEER_LOCALMSPID=dcentraMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dcentra.io/peers/peer2.dcentra.io/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:7051
      - 9053:7053
  
