version: '2'
services:
  orderer.climatecoop.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.climatecoop.com
    container_name: orderer.climatecoop.com
  peer0.dcentra.io:
    container_name: peer0.dcentra.io
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.dcentra.io
  
networks:
  blockchain:
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/24