version: '2'
services:
  orderer.climatecoop.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.climatecoop.com
    container_name: orderer.climatecoop.com
  peer0.lacambra.tech:
    container_name: peer0.lacambra.tech
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.lacambra.tech
  peer1.lacambra.tech:
    container_name: peer1.lacambra.tech
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.lacambra.tech
  peer2.lacambra.tech:
    container_name: peer2.lacambra.tech
    extends:
      file: base/docker-compose-base.yaml
      service: peer2.lacambra.tech
networks:
  blockchain:
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/24