version: '2'
services:
  peer-base:
    image: hyperledger/fabric-peer:1.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=policies-check_blockchain
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=debug
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=1000000000s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=${DEV}
    networks:
      - blockchain
